// Generated by CoffeeScript 1.3.3
(function() {
  var recieveMessage;

  window.onload = function() {
    var commandHandler, targetWindow;
    targetWindow = window.frames["client-frame"];
    commandHandler = new CrossDomainCommandHandler(targetWindow);
    return commandHandler.addEventListener("testCall", recieveMessage);
  };

  recieveMessage = function(message) {
    var messageElement;
    messageElement = document.getElementById("message-output");
    messageElement.innerHTML = message;
    return ["This is the server answer, I recieved message: " + message, "second argument"];
  };

}).call(this);
